# Generated by Django 5.2.8 on 2025-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0004_alter_consultation_consultation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="status",
        ),
        migrations.AlterField(
            model_name="consultation",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="실제 상담 일시"
            ),
        ),
    ]
