# Generated by Django 5.2.8 on 2025-12-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0005_remove_consultation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="preferred_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="희망 상담 일자"
            ),
        ),
    ]
