# Generated by Django 5.2.8 on 2025-12-04 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0006_consultation_preferred_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "신청완료"),
                    ("APPROVED", "상담예정"),
                    ("COMPLETED", "상담완료"),
                    ("CANCELED", "취소됨"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
