# Generated by Django 5.2.8 on 2025-12-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="과제 제목")),
                ("description", models.TextField(verbose_name="과제 설명")),
                ("due_date", models.DateTimeField(verbose_name="마감일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "과제",
                "verbose_name_plural": "과제",
                "db_table": "assignment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField(verbose_name="주차")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "결석"), (1, "출석"), (2, "지각")],
                        default=1,
                        verbose_name="출결 상태",
                    ),
                ),
                ("attendance_date", models.DateField(verbose_name="출결일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록일"),
                ),
            ],
            options={
                "verbose_name": "출결",
                "verbose_name_plural": "출결",
                "db_table": "attendance",
                "ordering": ["week", "student"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="수강 신청일"),
                ),
            ],
            options={
                "verbose_name": "수강 신청",
                "verbose_name_plural": "수강 신청",
                "db_table": "enrollment",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="수업명")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECRUITING", "선생님 배정 중"),
                            ("OPEN", "수강 신청 중"),
                            ("IN_PROGRESS", "수업 진행 중"),
                            ("CLOSED", "마감"),
                        ],
                        default="RECRUITING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "course_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="강의 코드",
                    ),
                ),
                (
                    "competency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "디지털"),
                            ("I", "인공지능"),
                            ("M", "메이킹"),
                            ("C", "컴퓨팅"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="역량 타입",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("common", "공통"),
                            ("basic", "기초"),
                            ("intermediate", "중급"),
                            ("advanced", "심화"),
                        ],
                        default="basic",
                        max_length=15,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "required_score",
                    models.IntegerField(default=0, verbose_name="최소 요구 점수"),
                ),
                (
                    "learning_tools",
                    models.TextField(blank=True, null=True, verbose_name="학습 도구"),
                ),
                (
                    "required_kits",
                    models.TextField(blank=True, null=True, verbose_name="필요 키트"),
                ),
            ],
            options={
                "verbose_name": "강의",
                "verbose_name_plural": "강의",
                "db_table": "lecture",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="지원 메시지"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("APPROVED", "승인됨"),
                            ("REJECTED", "반려됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="지원일"),
                ),
            ],
            options={
                "verbose_name": "강사 지원",
                "verbose_name_plural": "강사 지원",
                "db_table": "lecture_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("body", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "강의 공지사항",
                "verbose_name_plural": "강의 공지사항",
                "db_table": "lecture_notice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_score", models.FloatField(verbose_name="추천 점수")),
                ("reason", models.TextField(verbose_name="추천 이유")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "강의 추천",
                "verbose_name_plural": "강의 추천",
                "db_table": "lecture_recommendation",
                "ordering": ["-recommendation_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
            ],
            options={
                "verbose_name": "강의 스케줄",
                "verbose_name_plural": "강의 스케줄",
                "db_table": "lecture_schedule",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="제출 내용")),
                (
                    "file_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="첨부 파일 URL"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출일"),
                ),
                (
                    "grade",
                    models.IntegerField(blank=True, null=True, verbose_name="점수"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="피드백"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="채점일"),
                ),
            ],
            options={
                "verbose_name": "과제 제출",
                "verbose_name_plural": "과제 제출",
                "db_table": "submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가일"),
                ),
            ],
            options={
                "verbose_name": "관심 강의",
                "verbose_name_plural": "관심 강의",
                "db_table": "wishlist",
                "ordering": ["-created_at"],
            },
        ),
    ]
