# Generated by Django 5.2.8 on 2025-12-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_url',
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='첨부 파일'),
        ),
    ]
