# Generated by Django 5.2.8 on 2025-11-18 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_attendance_enrollment_lecturenotice_registration_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='lectureapplication',
            old_name='applied',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='lectureapplication',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='lectureapplication',
            name='received',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('RECRUITING', '강사 모집 중'), ('OPEN', '수강 신청 중'), ('CLOSED', '마감')], default='RECRUITING', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lectureapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lectureapplication',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lectureapplication',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_applications', to='lecture.lecture'),
        ),
        migrations.AlterField(
            model_name='lecturenotice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('lecture', 'student')},
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
