# Generated by Django 5.2.8 on 2025-12-03 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0003_alter_lecture_name_alter_lecture_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="competency_type",
            field=models.CharField(
                blank=True,
                choices=[("D", "디지털"), ("I", "인공지능"), ("M", "메이킹"), ("C", "컴퓨팅")],
                max_length=1,
                null=True,
                verbose_name="역량 타입",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="course_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="강의 코드"
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="learning_tools",
            field=models.TextField(blank=True, null=True, verbose_name="학습 도구"),
        ),
        migrations.AddField(
            model_name="lecture",
            name="level",
            field=models.CharField(
                choices=[
                    ("common", "공통"),
                    ("basic", "기초"),
                    ("intermediate", "중급"),
                    ("advanced", "심화"),
                ],
                default="basic",
                max_length=15,
                verbose_name="난이도",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="prerequisite_lectures",
            field=models.ManyToManyField(
                blank=True,
                related_name="next_lectures",
                to="lecture.lecture",
                verbose_name="선수과목",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="required_kits",
            field=models.TextField(blank=True, null=True, verbose_name="필요 키트"),
        ),
        migrations.AddField(
            model_name="lecture",
            name="required_score",
            field=models.IntegerField(default=0, verbose_name="최소 요구 점수"),
        ),
        migrations.CreateModel(
            name="LectureRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_score", models.FloatField(verbose_name="추천 점수")),
                ("reason", models.TextField(verbose_name="추천 이유")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="lecture.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recommendation_score", "-created_at"],
                "unique_together": {("user", "lecture")},
            },
        ),
    ]
