# Generated by Django 5.2.8 on 2025-12-04 15:51

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0004_lecture_competency_type_lecture_course_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["week", "student"]},
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="user",
            new_name="student",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="content",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="deadline",
        ),
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(default="", verbose_name="과제 설명"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 4, 15, 51, 2, 28611, tzinfo=datetime.timezone.utc
                ),
                verbose_name="마감일",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=200, verbose_name="과제 제목"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(verbose_name="출결일"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.IntegerField(
                choices=[(0, "결석"), (1, "출석"), (2, "지각")],
                default=1,
                verbose_name="출결 상태",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="week",
            field=models.IntegerField(verbose_name="주차"),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("lecture", "student", "week")},
        ),
        migrations.AlterModelTable(
            name="attendance",
            table="attendance",
        ),
    ]
