# Generated by Django 5.2.8 on 2025-12-04 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0005_alter_attendance_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "과제",
                "verbose_name_plural": "과제",
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["week", "student"],
                "verbose_name": "출결",
                "verbose_name_plural": "출결",
            },
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "수강 신청",
                "verbose_name_plural": "수강 신청",
            },
        ),
        migrations.AlterModelOptions(
            name="lecture",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "강의",
                "verbose_name_plural": "강의",
            },
        ),
        migrations.AlterModelOptions(
            name="lectureapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "강사 지원",
                "verbose_name_plural": "강사 지원",
            },
        ),
        migrations.AlterModelOptions(
            name="lecturenotice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "강의 공지사항",
                "verbose_name_plural": "강의 공지사항",
            },
        ),
        migrations.AlterModelOptions(
            name="lecturerecommendation",
            options={
                "ordering": ["-recommendation_score", "-created_at"],
                "verbose_name": "강의 추천",
                "verbose_name_plural": "강의 추천",
            },
        ),
        migrations.AlterModelOptions(
            name="lectureschedule",
            options={
                "ordering": ["start_date"],
                "verbose_name": "강의 스케줄",
                "verbose_name_plural": "강의 스케줄",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "관심 강의",
                "verbose_name_plural": "관심 강의",
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="기록일",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lecturenotice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AddField(
            model_name="lectureschedule",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="종료일"),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="추가일",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(verbose_name="과제 설명"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="학생",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="수강 신청일"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="학생",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lectures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="강사",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECRUITING", "선생님 배정 중"),
                    ("OPEN", "수강 신청 중"),
                    ("IN_PROGRESS", "수업 진행 중"),
                    ("CLOSED", "마감"),
                ],
                default="RECRUITING",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="lectureapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="지원일"),
        ),
        migrations.AlterField(
            model_name="lectureapplication",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applied_lectures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="강사",
            ),
        ),
        migrations.AlterField(
            model_name="lectureapplication",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_applications",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="lectureapplication",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="지원 메시지"),
        ),
        migrations.AlterField(
            model_name="lectureapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "대기 중"),
                    ("APPROVED", "승인됨"),
                    ("REJECTED", "반려됨"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="lecturenotice",
            name="body",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="lecturenotice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="lecturenotice",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecture_notices",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="lecturenotice",
            name="title",
            field=models.CharField(max_length=255, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="lecturerecommendation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="lecturerecommendation",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="lecturerecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecture_recommendations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="lectureschedule",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="lectureschedule",
            name="start_date",
            field=models.DateField(verbose_name="시작일"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to="lecture.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("lecture", "user")},
        ),
        migrations.AlterModelTable(
            name="assignment",
            table="assignment",
        ),
        migrations.AlterModelTable(
            name="enrollment",
            table="enrollment",
        ),
        migrations.AlterModelTable(
            name="lecture",
            table="lecture",
        ),
        migrations.AlterModelTable(
            name="lectureapplication",
            table="lecture_application",
        ),
        migrations.AlterModelTable(
            name="lecturenotice",
            table="lecture_notice",
        ),
        migrations.AlterModelTable(
            name="lecturerecommendation",
            table="lecture_recommendation",
        ),
        migrations.AlterModelTable(
            name="lectureschedule",
            table="lecture_schedule",
        ),
        migrations.AlterModelTable(
            name="wishlist",
            table="wishlist",
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="제출 내용")),
                (
                    "file_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="첨부 파일 URL"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출일"),
                ),
                (
                    "grade",
                    models.IntegerField(blank=True, null=True, verbose_name="점수"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="피드백"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="채점일"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lecture.assignment",
                        verbose_name="과제",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "과제 제출",
                "verbose_name_plural": "과제 제출",
                "db_table": "submission",
                "ordering": ["-submitted_at"],
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
