# Generated by Django 5.2.8 on 2025-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_lecturenotice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
