# Generated by Django 5.2.8 on 2025-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_attendance_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABSENT'), (1, 'PRESENT'), (2, 'LATE')], default=0),
        ),
    ]
