# Generated by Django 5.2.8 on 2025-12-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_ai_score_user_computing_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Manager'), (1, 'Student'), (2, 'Instructor')], default=1, verbose_name='역할'),
        ),
    ]
