# Generated by Django 5.2.8 on 2025-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_score",
            field=models.IntegerField(default=0, verbose_name="인공지능 역량"),
        ),
        migrations.AddField(
            model_name="user",
            name="computing_score",
            field=models.IntegerField(default=0, verbose_name="컴퓨팅 역량"),
        ),
        migrations.AddField(
            model_name="user",
            name="digital_score",
            field=models.IntegerField(default=0, verbose_name="디지털 역량"),
        ),
        migrations.AddField(
            model_name="user",
            name="making_score",
            field=models.IntegerField(default=0, verbose_name="메이킹 역량"),
        ),
    ]
