# Generated by Django 5.2.8 on 2025-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_delete_lecturenotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
