# Generated by Django 3.1.3 on 2025-11-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureNotice',
        ),
    ]
